### ISSUE TITLE
ad filtering / refinement if possible

### ISSUE THREAD

**Issue by agoza** [mptwaktusolat/app_waktu_solat_malaysia#177]
![Screenshot_2023-02-17-20-40-05-325_live iqfareez waktusolatmalaysia](https://user-images.githubusercontent.com/49515501/219656384-e51195b8-53e8-45fc-9560-bf3ea76ceb1c.jpg)
![Screenshot_2023-02-17-20-33-47-200_live iqfareez waktusolatmalaysia](https://user-images.githubusercontent.com/49515501/219656390-db964566-3df5-4c43-99e2-2f5d32291e27.jpg)
Shein app ad showing _a bit_ too much skin amirite. Please delete this issue once aware ✌️

**Comment by iqfareez** [comment]
Thank you for your report @agoza. I've blocked SHEIN from App Install Ads.

![20230218_071517.jpg](https://user-images.githubusercontent.com/60868965/219814902-0fcdc49d-294c-4862-a4a0-de10bf56d2a9.jpg)

Other than that, all of the sensitive categories Ads have already been blocked. 

![20230218_071913.jpg](https://user-images.githubusercontent.com/60868965/219815281-77834f0b-c026-4a28-a540-f77b3762d112.jpg)

Closing for now, feel free to reopen if any more Ads that are disturbing.
